frontend_ofertas:
    pattern:  /ofertas
    defaults: { _controller: FrontendBundle:Default:index }
    options:
       expose: true

frontend_mappings:
    pattern: /frontal/mappings
    defaults: { _controller: FrontendBundle:Default:mappings }
    options:
        expose: true

frontend_homepage:
    pattern: /
    defaults: { _controller: FrontendBundle:Default:homepage }