menu:
    path:     /
    defaults: { _controller: "BackendBundle:Menu:index" }

menu_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Menu:show" }

menu_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Menu:new" }

menu_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Menu:create" }
    requirements: { _method: post }

menu_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Menu:edit" }

menu_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Menu:update" }
    requirements: { _method: post|put }

menu_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Menu:delete" }
    requirements: { _method: post|delete }


#AJAX
menu_ajax_add:
    path: /add/issue/
    defaults: { _controller: "BackendBundle:Menu:addMenu"  }
    requirements: { _method: post }
    options:
        expose: true
menu_ajax_edit:
    path: /edit/issue/
    defaults: { _controller: "BackendBundle:Menu:editMenu"  }
    requirements: { _method: post }
    options:
        expose: true
