backend_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BackendBundle:Default:index }

backend_bundle_oferta:
    resource: "@BackendBundle/Resources/config/routing/oferta.yml"
    prefix: /oferta

backend_bundle_menu:
    resource: "@BackendBundle/Resources/config/routing/menu.yml"
    prefix: /menu

#HomePage
admin:
    pattern: /
    defaults: {  _controller: "BackendBundle:Oferta:ofertas" }