parameters:
#    backend.example.class: Fran\BackendBundle\Example

services:
#    backend.example:
#        class: %backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     oferta.namer:
         class: Fran\BackendBundle\Namer\OfertaNamer
